<?php

/**
 * Dialyra flow graph decompiler.
 *
 * Reconstructs the menu-oriented frontend flow JSON from Dialyra nodes/edges
 * generated by Dialyra_Flow_Compiler.
 *
 * @package Wp_Dialyra
 * @subpackage Wp_Dialyra/includes/flow
 */

if ( ! defined( 'WPINC' ) ) {
	die;
}

class Dialyra_Flow_Graph_Decompiler {

	const END_NODE_KEY = 'flow_end';

	/**
	 * Nodes by node key.
	 *
	 * @since 1.0.0
	 * @var array
	 */
	private $nodes = array();

	/**
	 * Edges grouped by source node key.
	 *
	 * @since 1.0.0
	 * @var array
	 */
	private $edges_by_source = array();

	/**
	 * Decompile graph data into frontend flow JSON.
	 *
	 * @since    1.0.0
	 * @param    array    $flow     Flow data.
	 * @param    array    $nodes    Flow nodes.
	 * @param    array    $edges    Flow edges.
	 * @return   array
	 */
	public function decompile( $flow, $nodes, $edges ) {
		$flow  = is_array( $flow ) ? $flow : array();
		$nodes = is_array( $nodes ) ? $nodes : array();
		$edges = is_array( $edges ) ? $edges : array();

		$this->index_graph( $nodes, $edges );

		$menu_ids      = $this->detect_menu_ids();
		$menu_ids      = ! empty( $menu_ids ) ? $menu_ids : array( 'main_menu' );
		$start_menu_id = $this->detect_start_menu_id( $flow, $menu_ids );
		$menus         = array();

		foreach ( $menu_ids as $menu_id ) {
			$menus[] = $this->decompile_menu( $menu_id, $start_menu_id );
		}

		return array(
			'name'            => ! empty( $flow['name'] ) ? sanitize_text_field( $flow['name'] ) : __( 'Untitled flow', 'wp-dialyra' ),
			'description'     => ! empty( $flow['description'] ) ? sanitize_text_field( $flow['description'] ) : '',
			'startMenuId'     => $start_menu_id,
			'menus'           => $menus,
			'transferFailed'  => $this->decompile_transfer_fallback( 'failed', $start_menu_id ),
			'transferTimeout' => $this->decompile_transfer_fallback( 'timeout', $start_menu_id ),
		);
	}

	/**
	 * Index nodes and edges by stable node keys.
	 *
	 * @since    1.0.0
	 * @param    array    $nodes    Nodes.
	 * @param    array    $edges    Edges.
	 */
	private function index_graph( $nodes, $edges ) {
		$this->nodes           = array();
		$this->edges_by_source = array();

		$node_ids = array();

		foreach ( $nodes as $node ) {
			$node = is_array( $node ) ? $node : array();
			$key  = $this->node_key( $node['node_key'] ?? '' );

			if ( '' === $key ) {
				continue;
			}

			$node['node_key'] = $key;
			$node['config']   = $this->array_value( $node['config'] ?? array() );

			$this->nodes[ $key ] = $node;

			if ( ! empty( $node['id'] ) ) {
				$node_ids[ absint( $node['id'] ) ] = $key;
			}
		}

		foreach ( $edges as $edge ) {
			$edge = is_array( $edge ) ? $edge : array();

			$source_key = $this->node_key( $edge['source_node_key'] ?? '' );
			$target_key = $this->node_key( $edge['target_node_key'] ?? '' );

			if ( '' === $source_key && ! empty( $edge['source_node_id'] ) && isset( $node_ids[ absint( $edge['source_node_id'] ) ] ) ) {
				$source_key = $node_ids[ absint( $edge['source_node_id'] ) ];
			}

			if ( '' === $target_key && ! empty( $edge['target_node_id'] ) && isset( $node_ids[ absint( $edge['target_node_id'] ) ] ) ) {
				$target_key = $node_ids[ absint( $edge['target_node_id'] ) ];
			}

			if ( '' === $source_key || '' === $target_key ) {
				continue;
			}

			$edge['source_node_key'] = $source_key;
			$edge['target_node_key'] = $target_key;
			$edge['condition_type']  = sanitize_key( $edge['condition_type'] ?? 'always' );
			$edge['condition_value'] = isset( $edge['condition_value'] ) ? sanitize_text_field( $edge['condition_value'] ) : '';
			$edge['priority']        = isset( $edge['priority'] ) ? absint( $edge['priority'] ) : 1;

			if ( ! isset( $this->edges_by_source[ $source_key ] ) ) {
				$this->edges_by_source[ $source_key ] = array();
			}

			$this->edges_by_source[ $source_key ][] = $edge;
		}

		foreach ( $this->edges_by_source as $source_key => $source_edges ) {
			usort(
				$source_edges,
				static function ( $first, $second ) {
					return ( $first['priority'] ?? 1 ) <=> ( $second['priority'] ?? 1 );
				}
			);

			$this->edges_by_source[ $source_key ] = $source_edges;
		}
	}

	/**
	 * Detect menu IDs from compiler-generated message/gather pairs.
	 *
	 * @since    1.0.0
	 * @return   array
	 */
	private function detect_menu_ids() {
		$menu_ids = array();

		foreach ( array_keys( $this->nodes ) as $node_key ) {
			if ( preg_match( '/^menu_(.+)_message$/', $node_key, $matches ) ) {
				$menu_ids[] = $matches[1];
			}
		}

		return array_values( array_unique( $menu_ids ) );
	}

	/**
	 * Detect start menu.
	 *
	 * @since    1.0.0
	 * @param    array    $flow       Flow.
	 * @param    array    $menu_ids   Menu IDs.
	 * @return   string
	 */
	private function detect_start_menu_id( $flow, $menu_ids ) {
		foreach ( $this->nodes as $node_key => $node ) {
			if ( ! empty( $node['is_start'] ) && preg_match( '/^menu_(.+)_message$/', $node_key, $matches ) ) {
				return $matches[1];
			}
		}

		foreach ( $menu_ids as $menu_id ) {
			if ( 'main_menu' === $menu_id ) {
				return $menu_id;
			}
		}

		return ! empty( $menu_ids ) ? $menu_ids[0] : 'main_menu';
	}

	/**
	 * Decompile one menu.
	 *
	 * @since    1.0.0
	 * @param    string    $menu_id         Menu ID.
	 * @param    string    $start_menu_id   Start menu ID.
	 * @return   array
	 */
	private function decompile_menu( $menu_id, $start_menu_id ) {
		$message_key = $this->menu_message_key( $menu_id );
		$gather_key  = $this->menu_gather_key( $menu_id );
		$message     = $this->nodes[ $message_key ] ?? array();
		$gather      = $this->nodes[ $gather_key ] ?? array();
		$gather_config = $this->array_value( $gather['config'] ?? array() );
		$menu_name   = $this->menu_name_from_node( $message, $menu_id );

		return array(
			'id'                         => $menu_id,
			'name'                       => $menu_name,
			'isStart'                    => $menu_id === $start_menu_id,
			'description'                => '',
			'customerInstructionMessage' => $this->message_from_node( $message ),
			'inputSettings'              => array(
				'maxDigits'         => max( 1, absint( $gather_config['max_digits'] ?? 1 ) ),
				'timeoutSeconds'    => max( 1, absint( $gather_config['timeout_seconds'] ?? 5 ) ),
				'maxInvalidRetries' => isset( $gather_config['max_invalid_retries'] ) ? absint( $gather_config['max_invalid_retries'] ) : 2,
				'maxTimeoutRetries' => isset( $gather_config['max_timeout_retries'] ) ? absint( $gather_config['max_timeout_retries'] ) : 1,
			),
			'dtmfActions'                => $this->decompile_dtmf_actions( $menu_id ),
			'invalidInputHandling'       => $this->decompile_menu_fallback( $menu_id, 'invalid_input', 'invalid_response', 'afterMaxInvalidRetryAction' ),
			'timeoutHandling'            => $this->decompile_menu_fallback( $menu_id, 'timeout', 'timeout_response', 'nextStep' ),
		);
	}

	/**
	 * Decompile DTMF actions for one menu.
	 *
	 * @since    1.0.0
	 * @param    string    $menu_id    Menu ID.
	 * @return   array
	 */
	private function decompile_dtmf_actions( $menu_id ) {
		$gather_key = $this->menu_gather_key( $menu_id );
		$actions    = array();

		if ( ! isset( $this->nodes[ $gather_key ] ) ) {
			return $actions;
		}

		foreach ( $this->edges_by_source[ $gather_key ] ?? array() as $edge ) {
			if ( 'dtmf' !== $edge['condition_type'] || '' === ( $edge['condition_value'] ?? '' ) ) {
				continue;
			}

			$input_key = sanitize_text_field( $edge['condition_value'] );
			$chain     = $this->follow_action_chain( $edge['target_node_key'], $menu_id, $input_key );

			$actions[] = array(
				'inputKey'        => $input_key,
				'responseMessage' => $chain['responseMessage'],
				'businessAction'  => $chain['businessAction'],
				'nextStep'        => $chain['nextStep'],
			);
		}

		return $actions;
	}

	/**
	 * Follow a generated DTMF chain.
	 *
	 * @since    1.0.0
	 * @param    string    $entry_key   Entry node key.
	 * @param    string    $menu_id     Menu ID.
	 * @param    string    $input_key   Input key.
	 * @return   array
	 */
	private function follow_action_chain( $entry_key, $menu_id, $input_key ) {
		$response        = array( 'type' => 'none' );
		$business_action = array( 'type' => 'no_action' );
		$next_target     = $entry_key;
		$current_key     = $entry_key;
		$visited         = array();

		while ( '' !== $current_key && isset( $this->nodes[ $current_key ] ) && empty( $visited[ $current_key ] ) ) {
			$visited[ $current_key ] = true;
			$node                   = $this->nodes[ $current_key ];
			$node_type              = sanitize_key( $node['node_type'] ?? '' );
			$config                 = $this->array_value( $node['config'] ?? array() );

			if ( 'set_variable' === $node_type && 'order_action' === ( $config['key'] ?? '' ) ) {
				$value = sanitize_key( $config['value'] ?? '' );

				if ( 'confirmed' === $value ) {
					$business_action = array( 'type' => 'confirm_order' );
				} elseif ( 'cancelled' === $value ) {
					$business_action = array( 'type' => 'cancel_order' );
				}
			} elseif ( in_array( $node_type, array( 'say_text', 'tts', 'play_audio' ), true ) && $current_key === $this->dtmf_node_key( $menu_id, $input_key, 'response' ) ) {
				$response = $this->message_from_node( $node );
			} elseif ( 'transfer_call' === $node_type && 'department' === sanitize_key( $config['target_type'] ?? '' ) ) {
				$business_action = array(
					'type'         => 'transfer_department',
					'departmentId' => absint( $config['department_id'] ?? 0 ),
				);

				$transfer_edge = $this->find_edge( $current_key, 'transfer_connected' );
				$next_target   = $transfer_edge ? $transfer_edge['target_node_key'] : self::END_NODE_KEY;
				break;
			}

			$always_edge = $this->find_edge( $current_key, 'always' );

			if ( ! $always_edge ) {
				$next_target = $current_key;
				break;
			}

			$next_target = $always_edge['target_node_key'];
			$current_key = $next_target;

			if ( $this->is_next_step_target( $current_key ) ) {
				break;
			}
		}

		return array(
			'responseMessage' => $response,
			'businessAction'  => $business_action,
			'nextStep'        => $this->next_step_from_target( $next_target, $menu_id ),
		);
	}

	/**
	 * Decompile invalid/timeout handling.
	 *
	 * @since    1.0.0
	 * @param    string    $menu_id          Menu ID.
	 * @param    string    $condition_type   Edge condition type.
	 * @param    string    $response_suffix  Response node suffix.
	 * @param    string    $action_key       Output action key.
	 * @return   array
	 */
	private function decompile_menu_fallback( $menu_id, $condition_type, $response_suffix, $action_key ) {
		$edge = $this->find_edge( $this->menu_gather_key( $menu_id ), $condition_type );
		$response = array( 'type' => 'none' );
		$target   = $edge ? $edge['target_node_key'] : $this->menu_message_key( $menu_id );

		if ( $edge && $edge['target_node_key'] === 'menu_' . $menu_id . '_' . $response_suffix && isset( $this->nodes[ $edge['target_node_key'] ] ) ) {
			$response = $this->message_from_node( $this->nodes[ $edge['target_node_key'] ] );
			$always   = $this->find_edge( $edge['target_node_key'], 'always' );
			$target   = $always ? $always['target_node_key'] : $this->menu_message_key( $menu_id );
		}

		return array(
			'responseMessage' => $response,
			$action_key       => $this->next_step_from_target( $target, $menu_id ),
		);
	}

	/**
	 * Decompile global transfer failed/timeout fallback.
	 *
	 * @since    1.0.0
	 * @param    string    $mode            failed|timeout.
	 * @param    string    $start_menu_id   Start menu ID.
	 * @return   array
	 */
	private function decompile_transfer_fallback( $mode, $start_menu_id ) {
		$is_timeout   = 'timeout' === $mode;
		$response_key = $is_timeout ? 'global_transfer_timeout_response' : 'global_transfer_failed_response';
		$response     = array( 'type' => 'none' );
		$target       = self::END_NODE_KEY;

		if ( isset( $this->nodes[ $response_key ] ) ) {
			$response = $this->message_from_node( $this->nodes[ $response_key ] );
			$edge     = $this->find_edge( $response_key, 'always' );
			$target   = $edge ? $edge['target_node_key'] : self::END_NODE_KEY;
		}

		return array(
			'responseMessage' => $response,
			'nextStep'        => $this->next_step_from_target( $target, $start_menu_id ),
		);
	}

	/**
	 * Build frontend message config from a graph node.
	 *
	 * @since    1.0.0
	 * @param    array    $node    Node.
	 * @return   array
	 */
	private function message_from_node( $node ) {
		$node      = is_array( $node ) ? $node : array();
		$node_type = sanitize_key( $node['node_type'] ?? '' );
		$config    = $this->array_value( $node['config'] ?? array() );

		if ( 'play_audio' === $node_type ) {
			return array(
				'type'         => 'audio',
				'audioAssetId' => absint( $config['audio_asset_id'] ?? 0 ),
			);
		}

		if ( in_array( $node_type, array( 'say_text', 'tts' ), true ) ) {
			$text = sanitize_textarea_field( $config['text'] ?? '' );

			if ( '' === $text ) {
				$text = $this->message_placeholder_from_node( $node );
			}

			return array(
				'type'     => 'tts',
				'message'  => $text,
				'language' => ! empty( $config['language'] ) ? sanitize_text_field( $config['language'] ) : 'en',
				'provider' => ! empty( $config['provider'] ) ? sanitize_text_field( $config['provider'] ) : 'google',
				'voice'    => ! empty( $config['voice'] ) ? sanitize_text_field( $config['voice'] ) : 'gtts:free',
			);
		}

		return array( 'type' => 'none' );
	}

	/**
	 * Build a safe editable placeholder when API node config is empty.
	 *
	 * @since    1.0.0
	 * @param    array    $node    Node.
	 * @return   string
	 */
	private function message_placeholder_from_node( $node ) {
		$name = ! empty( $node['name'] ) ? sanitize_text_field( $node['name'] ) : '';

		if ( $name ) {
			return sprintf(
				/* translators: %s: node name. */
				__( 'Review and update this message for %s.', 'wp-dialyra' ),
				$name
			);
		}

		return __( 'Review and update this message.', 'wp-dialyra' );
	}

	/**
	 * Convert target node key into frontend next step.
	 *
	 * @since    1.0.0
	 * @param    string    $target_key       Target node key.
	 * @param    string    $current_menu_id  Current menu ID.
	 * @return   array
	 */
	private function next_step_from_target( $target_key, $current_menu_id ) {
		$target_key = $this->node_key( $target_key );

		if ( self::END_NODE_KEY === $target_key ) {
			return array( 'type' => 'hangup' );
		}

		if ( preg_match( '/^menu_(.+)_message$/', $target_key, $matches ) ) {
			if ( $matches[1] === $current_menu_id ) {
				return array( 'type' => 'repeat_current_menu' );
			}

			return array(
				'type'         => 'go_to_menu',
				'targetMenuId' => $matches[1],
			);
		}

		return array( 'type' => 'hangup' );
	}

	/**
	 * Find first edge from source with condition.
	 *
	 * @since    1.0.0
	 * @param    string    $source_key       Source node key.
	 * @param    string    $condition_type   Condition type.
	 * @return   array|null
	 */
	private function find_edge( $source_key, $condition_type ) {
		foreach ( $this->edges_by_source[ $source_key ] ?? array() as $edge ) {
			if ( $condition_type === $edge['condition_type'] ) {
				return $edge;
			}
		}

		return null;
	}

	/**
	 * Check if a node key is a terminal next-step target.
	 *
	 * @since    1.0.0
	 * @param    string    $node_key    Node key.
	 * @return   bool
	 */
	private function is_next_step_target( $node_key ) {
		return self::END_NODE_KEY === $node_key || (bool) preg_match( '/^menu_.+_message$/', $node_key );
	}

	/**
	 * Build menu name from node.
	 *
	 * @since    1.0.0
	 * @param    array     $node      Message node.
	 * @param    string    $menu_id   Menu ID.
	 * @return   string
	 */
	private function menu_name_from_node( $node, $menu_id ) {
		$name = ! empty( $node['name'] ) ? sanitize_text_field( $node['name'] ) : '';
		$name = preg_replace( '/\s+Message$/', '', $name );

		return $name ? $name : ucwords( str_replace( '_', ' ', $menu_id ) );
	}

	/**
	 * Build menu message key.
	 *
	 * @since    1.0.0
	 * @param    string    $menu_id    Menu ID.
	 * @return   string
	 */
	private function menu_message_key( $menu_id ) {
		return 'menu_' . $this->node_key( $menu_id ) . '_message';
	}

	/**
	 * Build menu gather key.
	 *
	 * @since    1.0.0
	 * @param    string    $menu_id    Menu ID.
	 * @return   string
	 */
	private function menu_gather_key( $menu_id ) {
		return 'menu_' . $this->node_key( $menu_id ) . '_gather';
	}

	/**
	 * Build DTMF node key.
	 *
	 * @since    1.0.0
	 * @param    string    $menu_id      Menu ID.
	 * @param    string    $input_key    Input key.
	 * @param    string    $suffix       Suffix.
	 * @return   string
	 */
	private function dtmf_node_key( $menu_id, $input_key, $suffix ) {
		return 'menu_' . $this->node_key( $menu_id ) . '_dtmf_' . $this->node_key( $input_key ) . '_' . $this->node_key( $suffix );
	}

	/**
	 * Sanitize a graph key.
	 *
	 * @since    1.0.0
	 * @param    mixed    $value    Value.
	 * @return   string
	 */
	private function node_key( $value ) {
		return sanitize_key( str_replace( '-', '_', is_scalar( $value ) ? (string) $value : '' ) );
	}

	/**
	 * Normalize array value, including JSON strings.
	 *
	 * @since    1.0.0
	 * @param    mixed    $value    Value.
	 * @return   array
	 */
	private function array_value( $value ) {
		if ( is_array( $value ) ) {
			return $value;
		}

		if ( is_string( $value ) && '' !== $value ) {
			$decoded = json_decode( $value, true );

			return JSON_ERROR_NONE === json_last_error() && is_array( $decoded ) ? $decoded : array();
		}

		return array();
	}
}
